name: Robot Framework Tests

on:
  push:
    branches:
      - main  # Adjust to match your branch name

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11  # Specify the desired Python version
      - name: Install dependencies
        run: |
          pip install --upgrade robotframework 
          pip install --upgrade robotframework-browser
          rfbrowser init
      - name: Run Robot Framework tests
        run: |
          robot --outputdir test-reports/ robot_tests/test.robot
      - name: Upload RF test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: reports
          path: test-reports/
      - name: Publish Robot Framework test results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: ${{ always() && github.actor != 'dependabot[bot]' }}
        with:
          junit_files: test-reports/outputxunit.xml
          check_name: Robot Framework FE tests